# Translations template for aodh.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the aodh project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: aodh 0.0.1.dev3934\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-07-10 06:19+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: aodh/service.py:99
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: aodh/alarm/rpc.py:49
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: aodh/alarm/service.py:91
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: aodh/alarm/service.py:96
msgid "alarm evaluation cycle failed"
msgstr ""

#: aodh/alarm/service.py:101
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: aodh/alarm/service.py:105
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: aodh/alarm/service.py:109
#, python-format
msgid "Failed to evaluate alarm %s"
msgstr ""

#: aodh/alarm/service.py:177
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: aodh/alarm/service.py:186
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: aodh/alarm/service.py:192
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr ""

#: aodh/alarm/service.py:197
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: aodh/alarm/service.py:218
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: aodh/alarm/evaluator/__init__.py:75
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: aodh/alarm/evaluator/__init__.py:87
msgid "alarm state update failed"
msgstr ""

#: aodh/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: aodh/alarm/evaluator/combination.py:57
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: aodh/alarm/evaluator/combination.py:79
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: aodh/alarm/evaluator/combination.py:83
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: aodh/alarm/evaluator/combination.py:104 aodh/alarm/evaluator/gnocchi.py:214
#: aodh/alarm/evaluator/threshold.py:178
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:106 aodh/alarm/evaluator/threshold.py:89
#, python-format
msgid "stats query %s"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:110 aodh/alarm/evaluator/threshold.py:95
msgid "alarm stats retrieval failed"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:113
#, python-format
msgid "alarm stats retrieval failed: %s"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:128 aodh/alarm/evaluator/threshold.py:56
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:140 aodh/alarm/evaluator/threshold.py:112
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:163 aodh/alarm/evaluator/threshold.py:137
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:167 aodh/alarm/evaluator/threshold.py:141
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: aodh/alarm/evaluator/gnocchi.py:226 aodh/alarm/evaluator/threshold.py:197
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: aodh/alarm/evaluator/threshold.py:66
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: aodh/alarm/evaluator/threshold.py:75
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr ""

#: aodh/alarm/evaluator/threshold.py:84
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: aodh/alarm/notifier/log.py:31
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s of %(severity)s priority from"
" %(previous)s to %(current)s with action %(action)s because %(reason)s."
msgstr ""

#: aodh/alarm/notifier/rest.py:64
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s with severity %(severity)s "
"from %(previous)s to %(current)s with action %(action)s because "
"%(reason)s. request-id: %(request_id)s "
msgstr ""

#: aodh/api/app.py:114
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: aodh/api/app.py:115
msgid "Configuration:"
msgstr ""

#: aodh/api/app.py:119
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: aodh/api/app.py:123
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: aodh/api/middleware.py:109
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:88
#, python-format
msgid "Alarm quota exceeded for user %(u)s on project %(p)s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:170
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:285
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: aodh/api/controllers/v2/alarms.py:295
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:306
#, python-format
msgid "%(rule1)s and %(rule2)s cannot be set at the same time"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:322
#, python-format
msgid "duplicate actions are found: %s, remove duplicate ones"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:328
#, python-format
msgid "%(name)s count exceeds maximum value %(maximum)d"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:339
#, python-format
msgid "Unable to parse action %s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:342
#, python-format
msgid "Unsupported action %s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:345
#, python-format
msgid "You are not authorized to create action: %s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:531
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:541
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:542 aodh/api/controllers/v2/alarms.py:708
msgid "Alarm incorrect"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:600
msgid "state invalid"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:701
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: aodh/api/controllers/v2/alarms.py:707
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: aodh/api/controllers/v2/base.py:49
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: aodh/api/controllers/v2/base.py:58
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: aodh/api/controllers/v2/base.py:201
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: aodh/api/controllers/v2/base.py:206
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: aodh/api/controllers/v2/base.py:211
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: aodh/api/controllers/v2/base.py:221
#, python-format
msgid "Alarm %s not found"
msgstr ""

#: aodh/api/controllers/v2/base.py:223
#, python-format
msgid "Alarm %(alarm_id)s not found in project %(project)s"
msgstr ""

#: aodh/api/controllers/v2/query.py:202
#, python-format
msgid "Filter expression not valid: %s"
msgstr ""

#: aodh/api/controllers/v2/query.py:217
#, python-format
msgid "Order-by expression not valid: %s"
msgstr ""

#: aodh/api/controllers/v2/query.py:227
msgid "Limit should be positive"
msgstr ""

#: aodh/api/controllers/v2/query.py:319
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: aodh/api/controllers/v2/query.py:320
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: aodh/api/controllers/v2/alarm_rules/combination.py:39
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: aodh/api/controllers/v2/alarm_rules/combination.py:48
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr ""

#: aodh/api/controllers/v2/alarm_rules/combination.py:69
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr ""

#: aodh/api/controllers/v2/alarm_rules/threshold.py:93
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: aodh/storage/impl_hbase.py:87
msgid "Dropping HBase schema..."
msgstr ""

#: aodh/storage/impl_hbase.py:94
msgid "Cannot disable table but ignoring error"
msgstr ""

#: aodh/storage/impl_hbase.py:98
msgid "Cannot delete table but ignoring error"
msgstr ""

#: aodh/storage/models.py:70
msgid "timestamp should be datetime object"
msgstr ""

#: aodh/storage/models.py:72
msgid "state_timestamp should be datetime object"
msgstr ""

#: aodh/storage/hbase/base.py:45
msgid "Creating a new in-memory HBase Connection object"
msgstr ""

#: aodh/storage/hbase/base.py:62
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr ""

#: aodh/storage/hbase/inmemory.py:268
msgid "Opening in-memory HBase connection"
msgstr ""

#: aodh/storage/hbase/utils.py:225
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr ""

#: aodh/storage/mongo/utils.py:85
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: aodh/storage/mongo/utils.py:100
#, python-format
msgid "Unable to connect to the database server: %(errmsg)s."
msgstr ""

#: aodh/storage/mongo/utils.py:239
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb after %(retries)d retries. "
"Giving up."
msgstr ""

#: aodh/storage/mongo/utils.py:243
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

