# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
# Andi Chandler <andi@gowling.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-04 06:08+0000\n"
"PO-Revision-Date: 2014-07-25 15:11+0000\n"
"Last-Translator: Andi Chandler <andi@gowling.com>\n"
"Language-Team: English (United Kingdom) (http://www.transifex.com/projects/p/"
"ceilometer/language/en_GB/)\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Original exception being dropped: %s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Unexpected exception occurred %d time(s)... retrying."

#: ceilometer/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Could not release the acquired lock `%s`"

#: ceilometer/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "in fixed duration looping call"

#: ceilometer/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "in dynamic looping call"

#: ceilometer/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "Failed to understand rule %s"

#: ceilometer/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: ceilometer/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "Failed to understand rule %r"

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exception during rpc cleanup."

#: ceilometer/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Unhandled exception"

#: ceilometer/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DB exceeded retry limit."

#: ceilometer/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "DB connection error."

#: ceilometer/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "DB exception wrapped."

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr "Failed to migrate to version %s on engine %s"

#: ceilometer/openstack/common/middleware/catch_errors.py:40
#, python-format
msgid "An error occurred during processing the request: %s"
msgstr "An error occurred during processing the request: %s"
